# Generated by Django 3.2 on 2022-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220306_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Home Appliances', 'Home Appliances'), ('Groceries', 'Groceries'), ('Medical Aids', 'Medical Aids')], max_length=200, null=True)),
            ],
        ),
    ]
