# Generated by Django 3.2 on 2022-03-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Home Appliances', 'Home Appliances'), ('Groceries', 'Groceries'), ('Medical Aids', 'Medical Aids')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.productcategory'),
        ),
    ]
