# Generated by Django 3.2 on 2022-03-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
    ]
