# Generated by Django 3.2 on 2022-03-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220308_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Home Appliances', 'Home Appliances'), ('Groceries', 'Groceries'), ('Medical Aids', 'Medical Aids')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
