# Generated by Django 3.2 on 2022-03-08 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220308_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='procategory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product'),
        ),
    ]
