# Generated by Django 3.2 on 2022-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220308_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
