# Generated by Django 3.2 on 2022-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20220308_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
