# Generated by Django 3.2 on 2022-03-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220308_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.DeleteModel(
            name='cat',
        ),
    ]
